// SVG icon paths from Simple Icons (CDN) for well-known companies.
// Falls back to a generic building icon for unknowns.

const SLUG_MAP = {
  'amazon':     'amazon',
  'apple':      'apple',
  'google':     'google',
  'microsoft':  'microsoft',
  'netflix':    'netflix',
  'meta':       'meta',
  'facebook':   'meta',
  'uber':       'uber',
  'airbnb':     'airbnb',
  'adobe':      'adobe',
  'bloomberg':  'bloomberg',
  'linkedin':   'linkedin',
  'twitter':    'x',
  'x':          'x',
  'spotify':    'spotify',
  'salesforce': 'salesforce',
  'oracle':     'oracle',
  'ibm':        'ibm',
  'intel':      'intel',
  'nvidia':     'nvidia',
  'tesla':      'tesla',
  'lyft':       'lyft',
  'snap':       'snapchat',
  'snapchat':   'snapchat',
  'tiktok':     'tiktok',
  'bytedance':  'bytedance',
  'paypal':     'paypal',
  'stripe':     'stripe',
  'shopify':    'shopify',
  'atlassian':  'atlassian',
  'slack':      'slack',
  'zoom':       'zoom',
  'dropbox':    'dropbox',
  'twilio':     'twilio',
  'databricks': 'databricks',
  'snowflake':  'snowflake',
  'coinbase':   'coinbase',
  'robinhood':  'robinhood',
  'instacart':  'instacart',
  'doordash':   'doordash',
  'expedia':    'expedia',
  'booking':    'bookingdotcom',
  'agoda':      'agoda',
  'goldman sachs': 'goldmansachs',
  'jpmorgan':   'jpmorgan',
  'visa':       'visa',
  'mastercard': 'mastercard',
  'samsung':    'samsung',
  'qualcomm':   'qualcomm',
  'amd':        'amd',
  'cisco':      'cisco',
  'vmware':     'vmware',
  'sap':        'sap',
  'workday':    'workday',
  'servicenow': 'servicenow',
  'twitch':     'twitch',
  'reddit':     'reddit',
  'pinterest':  'pinterest',
  'square':     'square',
  'block':      'square',
  'palantir':   'palantir',
  'roblox':     'roblox',
  'unity':      'unity',
  'epic games': 'epicgames',
  'activision': 'activision',
  'yelp':       'yelp',
  'grubhub':    'grubhub',
  'wix':        'wix',
  'wordpress':  'wordpress',
}

export function getCompanyLogoUrl(name) {
  const key = name.toLowerCase()
  const slug = SLUG_MAP[key]
  if (!slug) return null
  // Simple Icons CDN — white icons, we colour them via CSS
  return `https://cdn.simpleicons.org/${slug}/ffffff`
}
